jenkinsci/ansicolor-plugin

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiColorBuildWrapper.java, src/main/java/hudson/plugins/ansicolor/AnsiColorMap.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/resources/hudson/plugins/ansicolor/AnsiColorBuildWrapper/global.jelly, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
To close issue #24, I implemented the ability to configure a default background and foreground color. If at least one of those is set, the console output will be contained within a div with the appropriate style attribute set. Note that #24 called for setting this in the color map, but I opted for a per-job configuration instead.
=> Default colors

src/main/java/hudson/plugins/ansicolor/AnsiColorMap.java
This is a fixup to commit 4ef902b that renamed member variables. The new
serialVersionUID was calculated using Java's "serialver" tool.
This is supposed to fix #57.
=> AnsiColorMap: Change the serialVersionUID

src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
Do not rely on the default encoding to be UTF-8.
=> AnsiHtmlOutputStreamTest: Fix testJapanese() on Windows

.classpath, .project, CHANGELOG.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
pom.xml changes: - increased dependency of jansi to 1.12
- fixed the pom error with animal-sniffer plugin
AnsiHtmlOutputStream changes:
- added method processSetForegroundColor with additional parameter boolean bright to handle the 90 to 97 colors.
=> Support high intensity ANSI colors #16 with jansi-1.12

CHANGELOG.md, README.md
Documentation for configuring pipeline (workflow) builds was given 2nd class citizen status and as such it isn't entirely clear from first glance it worked
Also updated to refer to newer pipeline plugin name (as well as older workflow name)
=> Promote pipeline configuration in README

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
Added support for italic, strikeout, framed and overline attributes.
Added missing handling for ATTRIBUTE_CONCEAL_OFF.
See also #89.
=> Italic and more

CHANGELOG.md, README.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/java/hudson/plugins/ansicolor/AnsiOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
This PR is an addition to #96, but also drops the depentency to jansi (because of massive version trouble).
I'd just grabbed jansi's AnsiOutputStream.java and put it into ansicolor source tree, so it has been moved from package `org.fusesource.jansi` to `hudson.plugins.ansicolor`.
With this change, ext color support works regardless which jansi version is used by jenkins or other plugins.
=> More colors no jansi

CHANGELOG.md, README.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
This PR adds support for `esc[38;…m` / `esc[48;…m` for 256 colors and 24 bit foreground / background colors. See also:
- #89
- #44
- https://issues.jenkins-ci.org/browse/JENKINS-24378
Please note, that this needs [jansi PR #72](https://github.com/fusesource/jansi/pull/72) to build & work. I'd increased the jansi version dependency in the `pom.xml` to `1.14-SNAPSHOT` to build locally.
Further, we run into a version bump as described in #95 which leads also to make 256 colors and 24 bit colors don't work (even if we have successfully build and all plugin tests passed).
As I found a way to got it work with Jenkins 1.653 (by just deleting jansi-1.9.jar), I'd found no way to make it work with Jenkins 2.x. As dblock commented in #95, we might have to wait until even the Jenkins guys will pick …
=> Added support for xterm 256 colors and 24 bit colors

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
Some terminals (xterm) supports two different 'character sets' ('G0' and
'G1'), which can be switched with 'SI' (shift in, '\017') and 'SO'
(shift out, '\016'). Each character set can be configured separately
and can be chosen from a list of pre-defined sets like 'ASCII Set' and
'Special Graphics'.
Running `TERM=xterm tput sgr0` to reset the terminal returns an escape
sequence starting with 'ESC ( 0', which selects the 'ASCII Set' for
'G0'. This currently is not understood by the Jenkins AnsiColor plugin.
Filter out those sequences, as they otherwise clutter the output.
<https://www.in-ulm.de/~mascheck/various/alternate_charset/> has a nice
description for characters sets
=> Filter out escape sequence 'character set' select

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
like select primary/n-th alternate font
Fixes #112
Quick test:
printf '\033[10m\n'
=> Ignore unknown SGR (Select Graphic Rendition) parameters

.travis.yml
This fixes the current build issue on Travis for Linux.
Currently Java 10 is the default on Travis but the project does not yet compile with Java 10. Specifying the desired JDK version is anyway a good idea.
The OSX build can also be fixed. But I would suggest to remove testing on OSX completely. I haven't seen it for other plugins. A plugin is anyway build centrally and provided in binary form. So testing the build on another platform doesn't really provide that much.
Another question is if the plugin should better be build using the Jenkins infrastructure - see https://github.com/jenkins-infra/pipeline-library and https://ci.jenkins.io/job/Plugins/.
Therefore I propose to replace the `.travis.yml` with `Jenkinsfile`.
=> Use Java 8 on Travis

CHANGELOG.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
[JENKINS-54133](https://issues.jenkins-ci.org/browse/JENKINS-54133). Does not attempt to pregenerate notes for all cases, and in fact this seems to be impossible, though more common cases could certainly be added as needed.
As noted in JIRA, reimplementing the plugin as a `ConsoleAnnotatorFactory` would be a better solution in many respects, as well as fully solving this issue, but this would be a more ambitious refactoring than I am prepared to take on at the moment as it would involve inverting the control flow of `AnsiOutputStream`. See the corresponding Blue Ocean https://github.com/jenkinsci/blueocean-plugin/pull/1325 for a very general idea.
=> [JENKINS-54133] Pregenerating console notes sent to agents for some common cases

src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java
I cannot see any reason why `LineTransformationOutputStream` is being used here. Nothing special happens at line breaks that I know of; the `AnsiHtmlOutputStream` processes things on a byte-by-byte basis. And the `eol` implementation was adding `flush` calls which probably caused poor performance when applied to a remote buffered stream (https://github.com/jenkinsci/workflow-api-plugin/pull/81).
=> Removing use of LineTransformationOutputStream

src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilterTest.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
Provides the test coverage I proposed in #128, and fixes some straightforward cases that are now tested.
Subsumes #129, without which input text lacking a final newline would not be sent at all, unless `println` and `flush` were called, at which point the result string would contain an extra newline.
=> Remote console note test coverage & fixes

pom.xml
The [parent pom already defines a repository with the same URL with the id `maven.jenkins-ci.org`](https://github.com/jenkinsci/plugin-pom/blob/1f691cf5dd69b5626716c6b1564f2d67d8f8af34/pom.xml#L808-L818). My local `~/.m2/settings.xml` specifies a password for this repo using that id, but this plugin overrides the id for the repository, which means that my local settings were ignored, so I was unable to publish my changes to Artifactory until @jglick pointed out what was going on.
I think it is better to be consistent with other plugins and remove the override here, but anyone releasing the plugin may need to change their local settings.xml after this change.
=> Remove explicit distributionManagement setting in the POM

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
Fixes #139.
The cause of the issue is that we were using byte indices as `String` indices, which does not work when the `String` contains characters that require than one byte in the target encoding. To fix the issue, this PR keeps track of the number of multi-byte characters we've seen and how many bytes they require, and uses that information to convert the byte count obtained from `incoming.getCount()` into an index into the original text.
I originally worked on this in #137 but extracted it here so it can be reviewed independently from the less-important issues in that PR.
=> Fix #139: Handle non-ASCII characters correctly when annotating text

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
Fixes #135.
This PR currently adds tests and fixes for 2 issues:
1. If an escape sequence is not closed at the end of a line, its tag cannot be closed and its style modifications will carry over to all subsequent lines.
* This PR currently closes all tags that are open at the end of a line and then reopens them on the next line so that ANSI sequences in the line can close those tags correctly. I am not sure whether this is the desired behavior, or if we should instead close any tags that are open at the end of a line and leave them closed for good.
2. When using a color map with a default foreground or background, the default foreground and background are not used.
* This PR handles default foreground and background settings. I am not sure how often default foreground/background colors …
=> Allow escape sequences to span multiple lines and support default fg/bg colors

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
Fixes #145 (specifically variant 2 noted in https://github.com/jenkinsci/ansicolor-plugin/issues/145#issuecomment-452858635). See also [JENKINS-55139](https://issues.jenkins-ci.org/browse/JENKINS-55139).
Some tools, such as Terraform and Ansible, emit SGR0 (`ESC [ 0 m`) ANSI sequences even when display settings have not been changed since the last occurrence of SGR0. Since display settings are unchanged, no HTML is emitted, so our way of hiding control sequences using MarkupText does not work correctly. In 0.5.x and earlier, this wasn't a problem because all ANSI sequences were filtered from the underlying stream unconditionally, but now we ignore the output of the stream, so we have to account for these redundant sequences. We could try to fix those tools specifically, but if at least 2 …
=> [JENKINS-55139] Handle redundant occurrences of SGR0 in logs

pom.xml, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
Bump structs from 1.17 to 1.20. See [the changelog](https://wiki.jenkins.io/display/JENKINS/Structs+plugin) and the full diff in [the compare view](https://github.com/jenkinsci/structs-plugin/compare/structs-parent-1.17...structs-parent-1.20).
The main issue with this upgrade was a test that started failing with this exception:
```
java.lang.IllegalArgumentException: WARNING: Unknown parameter(s) found for class type 'hudson.plugins.ansicolor.AnsiColorBuildWrapper': defaultBg,defaultFg
at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:322)
at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:474)
at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
at …
```
=> Bump structs from 1.17 to 1.20

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiColorBuildWrapper.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/main/resources/hudson/plugins/ansicolor/AnsiColorBuildWrapper/global.jelly, src/main/resources/hudson/plugins/ansicolor/AnsiColorBuildWrapper/help-globalColorMapName.html, src/test/java/hudson/plugins/ansicolor/ColorConsoleAnnotatorTest.java
This allows for configuring a global color map name.
This resolves #2.
=> Allow global setting

src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
Two of the tests use expected result strings with hard-coded `\n` as line separators. Jenkins, on the other hand, consults the host OS while generating output. As a result the test cases fail when run on a OS that doesn't use `\n` as a line separator (like Windows).
This fixes the issue and allows running tests in a OS-agnostic way.
=> Allow tests to be executed independently of the OS

Jenkinsfile, pom.xml, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
This PR allows for running tests on [ci.jenkins.io](http://ci.jenkins.io).
The used `buildPlugin.recommendedConfigurations()` contain (among others) 
`[ platform: "windows", jdk: "8", jenkins: recentLTS, javaLevel: "8" ],` so a separate CI service (AppVeyor or any other) would not be needed.
=> Provide a basic Jenkinsfile to utilize testing on jenkins

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java
Currently the plugin incorrectly handles control sequences like:
- `CUU` Cursor Up
- `CUD` Cursor Down
- `CUF` Cursor Forward
- `CUB` Cursor Back
- `EL` Erase in Line
Using many popular tools in a job, like `docker`, produces output similar to:
```
+ docker-compose down
Stopping container_1               ... 
Stopping container_2               ... 
Stopping container_3               ... 
[4A[2K
Stopping container_1               done
[4B[2A[2K
```
This PR contains a fix - the mentioned sequences will not produce any output - as well as a test case against regression.
Merging this may very well fix https://github.com/jenkinsci/ansicolor-plugin/issues/151 as the actual problem looks very similar.
=> Work with moving sequences

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
This is a fix for #172 
Problem was that "SGR Normal intensity" `ESC[22m` was handled correctly **only** if output already contained an html tag `b` opened for "SGR Bold" `ESC[1m` sequence. In other cases it caused no output tags to be generated and the sequence itself was also not commented out.
This PR adds commenting out of any attribute-changing sequence which does not produce output.
Additionally I've added implementation for "SGR Faint" `ESC[2m` similarly to "SGR Bold" `ESC[1m` along with tests.
=> 172 sgr effect normal intensity

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
This is a fix for #158 
`SGR`s with possibly switched options, like
`ESC[5;38m`
have been falling into the same category as
`ESC[38;5m`
but causing exceptions mid-run.
The actual sequence which triggered this (provided by the user)
`ESC[0;38m`
looks strange and I haven't been able to find its full meaning (if there is one) so the fix will allow it to be treated the same way as simply
`ESC[0m`
with no exceptions thrown.
=> Ensure extended color SGRs are recognized correctly

CHANGELOG.md, README.md, pom.xml
This PR improves the README by addressing a reasonable (in my opinion) request from #156 and adding status badges concerning:
- `ci.jenkins.io` build
- current plugin version
- amount of installs so far
=> Add instruction for installing via jenkins cli. Improve documentation.

pom.xml
The GitHub README is more detailed than the Jenkins wiki page and provides a better experience for the reader.
See the [blog post](https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/) and the [documentation page](https://www.jenkins.io/doc/developer/publishing/documentation/#documenting-plugins) for more details.
=> Use GitHub README as plugins.jenkins.io docs

src/main/java/hudson/plugins/ansicolor/AnsiOutputStream.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
This is a fix for #186 
The initial changes in #176 assumed that 256 color `SGR`s would always *begin* with `38;5`, like :
```
esc[38;5;<index>m
```
Turns out it is possible for them to have attribute(s) before them as well, like:
```
esc[1;38;5;<index>m
```
=> #186 Allow rendering more complex sgrs

src/main/java/hudson/plugins/ansicolor/AnsiColorBuildWrapper.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java
This introduces configuration form input field validation for `ansicolor` settings available under `/configure`. Most of the fields had no rules defined.
Specifically the PR adds the following:
- each custom color map name: 1-256 chars (till now it could be any length >0)
- each custom color literal: 1-64 chars (till now there was no validation)
- global color map name must match one of the color maps (till now it could be any string)
- setting global color map name to an empty string removes it entirely from settings (till now the empty string was saved as-is) - the same state as in a clean Jenkins installation
=> Validate configuration form field values before storing them.

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/main/java/hudson/plugins/ansicolor/action/ColorizedAction.java, src/test/java/hudson/plugins/ansicolor/AnsiColorStepTest.java, src/test/java/hudson/plugins/ansicolor/action/ColorizedActionTest.java
This is a fix for [JENKINS-61598](https://issues.jenkins-ci.org/browse/JENKINS-61598)
It probably got introduced as a side effect of #137
=> Leaky formatting

.editorconfig, pom.xml, src/main/java/hudson/plugins/ansicolor/action/ColorizedAction.java, src/test/java/hudson/plugins/ansicolor/action/ColorizedActionTest.java
This is a workaround for #193 
It recreates the old behavior of triggering the plugin on registration in a pipeline regardless of the actual line of script it's been defined in. In this mode it doesn't check log annotations. This should fix the behavior for everyone reporting `0.6.3` was working fine.
I am assuming that the problem is caused by that fact that log annotations generated in an agent are not getting picked up by the master. It is not possible to reproduce this no matter which Jenkins version (tried `2.176.3`, `2.204.1`) or agent version (tried images `jenkins/inbound-agent:4.3-4-alpine`, `jenkins/jnlp-slave:4.3-4-alpine` and a manually constructed agent on `openjdk:14` ) I use. There probably is something else (security settings?) enabled on a prod-running Jenkins that is not …
=> Running on agent

.mailmap, CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java, src/main/java/hudson/plugins/ansicolor/action/ActionNote.java, src/main/java/hudson/plugins/ansicolor/action/ColorizedAction.java, src/test/java/hudson/plugins/ansicolor/action/ColorizedActionTest.java
This adjustment addresses the problem of `timestamper` plugin decorating the global `logger` with functionality that writes anything to the log **only** if the line ends with a `LF` character, otherwise it gets lost.
The `ansicolor` annotates log lines where its own logic should start/stop with `ConsoleNote`s which get serialized without any special line ending. If those lines are not available in the log upon rendering the whole coloring is not enabled and any special chars end up in the output it their raw form.
=> 193 interaction timestamper

CHANGELOG.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiColorBuildWrapper.java, src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java, src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/main/java/hudson/plugins/ansicolor/action/ColorizedAction.java, src/test/java/hudson/plugins/ansicolor/AnsiColorStepTest.java, src/test/java/hudson/plugins/ansicolor/ColorConsoleAnnotatorTest.java, src/test/java/hudson/plugins/ansicolor/JenkinsTestSupport.java, src/test/java/hudson/plugins/ansicolor/action/ColorizedActionTest.java
Fixes #200 
All is pretty much described in the issue.
The PR adds a way for checking the currently active color map name in the currently running job run.
=> Render logs correctly for long running jobs which generate lots of logs

pom.xml, src/main/resources/hudson/plugins/ansicolor/AnsiColorBuildWrapper/global.jelly
Following https://www.jenkins.io/doc/developer/views/table-to-div-migration/
See https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/
I'm not sure if this is causing an issue but I'm working through all the plugins that appear with tabular markup in https://issues.jenkins.io/browse/JENKINS-64341
cc @tszmytka
=> Remove tabular markup on new Jenkins core

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/action/ShortlogActionCreator.java, src/test/java/hudson/plugins/ansicolor/action/ShortlogActionCreatorTest.java
=> 212 partial log output

Jenkinsfile, src/main/java/hudson/plugins/ansicolor/action/ShortlogActionCreator.java, src/test/java/hudson/plugins/ansicolor/JenkinsTestSupport.java, src/test/java/hudson/plugins/ansicolor/action/ShortlogActionCreatorIntegrationTest.java
Follow up to #212 
Adjustment making testing simpler + additional test case with slightly changed expectations.
See also jenkinsci/bom#402
=> Adjust tests to reflect code changes

CHANGELOG.md, pom.xml, src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java, src/test/java/hudson/plugins/ansicolor/AnsiColorStepTest.java, src/test/java/hudson/plugins/ansicolor/mock/plugins/pipeline/maven/WithMavenStep.java
=> #223 Work around withMaven step not passing on log line metadata

CHANGELOG.md, src/main/java/hudson/plugins/ansicolor/action/ShortlogActionCreator.java, src/test/java/hudson/plugins/ansicolor/AnsiColorBuildWrapperTest.java, src/test/java/hudson/plugins/ansicolor/AnsiColorStepTest.java, src/test/java/hudson/plugins/ansicolor/ColorConsoleAnnotatorTest.java, src/test/java/hudson/plugins/ansicolor/JenkinsTestSupport.java, src/test/java/hudson/plugins/ansicolor/action/ShortlogActionCreatorIntegrationTest.java, src/test/java/hudson/plugins/ansicolor/action/ShortlogActionCreatorTest.java
Currently the functionality allowing tailed log output to be colorized is executed at the very end of a build - after the log file has already been closed (`onFinalized`). This permits accurate calculation of the point where tailed output will begin and correct `ColorizedAction.Command.START` action injection. Upon rendering, the new action gets added to the output but since the log file has already been closed the new content is not persisted. As a result tailed log output looks fine until a Jenkins instance gets rebooted. After the restart it gets shown without any ansi code interpreted (full output is fine before and after reboot).
The PR fixes this by moving the execution a bit earlier - to `onCompleted`. This point in the lifecycle of a `WorkflowRun` happens before log file has been …
=> Trigger tailed log output colorization also after Jenkins restart

.github/CONTRIBUTING.md
This PR fixes the broken link in `CONTRIBUTING.md` file in this project.
**Fixes** #231
=> Fix link for CHANGELOG

pom.xml, src/test/java/hudson/plugins/ansicolor/action/ShortlogActionCreatorIntegrationTest.java
Somehow https://github.com/jenkinsci/workflow-job-plugin/pull/146 caused this test to fail. I tried to debug it but could not make sense of what was going on. The test was introduced in #198.
=> `ShortlogActionCreatorIntegrationTest.canAnnotateLongLogOutputInShortlogMultipleStepsLinesWholeFalse` failing

src/main/java/hudson/plugins/ansicolor/AnsiAttributeElement.java, src/main/java/hudson/plugins/ansicolor/AnsiColorConsoleLogFilter.java, src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java, src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java, src/main/java/hudson/plugins/ansicolor/ColorConsoleAnnotator.java, src/main/java/hudson/plugins/ansicolor/action/ShortlogActionCreator.java, src/test/java/hudson/plugins/ansicolor/AnsiHtmlOutputStreamTest.java, src/test/java/hudson/plugins/ansicolor/mock/kubernetes/pipeline/SecretsMasker.java, src/test/java/hudson/plugins/ansicolor/mock/logstash/pipeline/GlobalDecorator.java, src/test/java/hudson/plugins/ansicolor/mock/timestamper/pipeline/GlobalDecorator.java
Compatible with [plugin POM 4.32](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.32).
=> EOL JSR 305

.mvn/extensions.xml, pom.xml
=> Update build toolchain

.github/CONTRIBUTING.md
This PR updates the Jenkins plugin tutorial link.
=> chore(doc/contributing): replace the deprecated Wiki tutorial link by the jenkins.io doc one

pom.xml, src/test/java/hudson/plugins/ansicolor/AnsiColorStepTest.java, src/test/java/hudson/plugins/ansicolor/JenkinsTestSupport.java
Remove AssertJ which does not currently support Java 21. This also makes the test framework used in this plugin consistent with the test framework used in other Jenkins plugins and Jenkins core.
Ran the tests on Java 21 before and after this PR. The tests failed before and passed after.
=> Remove AssertJ for Java 21 support

src/main/java/hudson/plugins/ansicolor/AnsiColorMap.java
No need to use a third-party library for this when the Java Platform provides this functionality natively.
=> Migrate from Commons Lang 2 to native Java Platform functionality
